### ISSUE TITLE
Support async/await by default

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#113]
Main use case is to make `Action.perform` cleaner by using syntax like

```js
async perform(params) {
  let User = this.modelFor('user');
  let mailer = this.service('mailer');
  let user = await User.find(params.id);
  
  mailer.send('welcome', user);

  return user;
}
```

--------

### Initial Stub Results

I tried the async-generator transform and am getting the following error:

```
Error building your app:
Error: /Users/iradchenko/battleground/test/app/actions/index.js: You gave us a visitor for the node type "ForAwaitStatement" but it's not a valid type
    at verify (/Users/iradchenko/sandbox/denali/node_modules/babel-traverse/lib/visitors.js:196:13)
    at Object.explode (/Users/iradchenko/sandbox/denali/node_modules/babel-traverse/lib/visitors.js:72:3)
    at traverse (/Users/iradchenko/sandbox/denali/node_modules/babel-traverse/lib/index.js:77:12)
    at NodePath.traverse (/Users/iradchenko/sandbox/denali/node_modules/babel-traverse/lib/path/index.js:144:25)
    at exports.default (/Users/iradchenko/battleground/test/node_modules/babel-helper-remap-async-to-generator/lib/index.js:10:8)
    at PluginPass.Function (/Users/iradchenko/battleground/test/node_modules/babel-plugin-transform-async-to-generator/lib/index.js:13:56)
    at newFn (/Users/iradchenko/sandbox/denali/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/iradchenko/sandbox/denali/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/iradchenko/sandbox/denali/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/iradchenko/sandbox/denali/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/iradchenko/sandbox/denali/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/iradchenko/sandbox/denali/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/iradchenko/sandbox/denali/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/iradchenko/sandbox/denali/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/iradchenko/sandbox/denali/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/iradchenko/sandbox/denali/node_modules/babel-traverse/lib/context.js:150:16)
```

**Comment by davewasmer** [comment]
So i don't have a ton of hands-on experience with async/await, but it's certainly intriguing. As I understand it, an async function interops with non-async functions by simply returning a promise, right?

If that's the case, it sounds like there should be nothing stopping a Action's responder method from being async, since Denali handles returned promises (obviously theres some kind of transpilation issue happening, but I'm thinking more on a conceptual level).

**Comment by davewasmer** [comment]
This should be resolved on master now. Feel free to reopen/refile if we are still missing something though.
