### ISSUE TITLE
[Bug] Add-on issue when running against latest version of master

### ISSUE THREAD

**Issue by acorncom** [denali-js/denali#130]
I'm hitting a bug in the latest broccoli-based build code.  Don't have time to track it down atm so thought I'd throw it up here so we could all take a look:

```
machine:~/Sites/ember-learn/ember-help-wanted-backend (master)$ denali server --watch

./denali-js/denali/lib/utils/discover-addons.js:63
    environment: parent.environment,
                 ^
TypeError: Cannot read property 'environment' of undefined
    at createAddonFromDirectory (./denali-js/denali/lib/utils/discover-addons.js:63:18)
    at ./denali-js/denali/lib/utils/discover-addons.js:30:19
    at ./denali-js/denali/node_modules/lodash/_createBaseFor.js:17:11
    at forIn (./denali-js/denali/node_modules/lodash/forIn.js:36:7)
    at discoverAddons (./denali-js/denali/lib/utils/discover-addons.js:22:3)
    at new Project (./denali-js/denali/lib/cli/lib/project.js:29:19)
    at ServerCommand.run (./denali-js/denali/lib/cli/commands/server.js:73:20)
    at ServerCommand._run (./denali-js/denali/lib/cli/lib/command.js:120:10)
    at Object.<anonymous> (./denali-js/denali/lib/cli/commands/index.js:90:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
```

You should be able to replicate this by using `master` on `ember-help-wanted-backend` linked to the latest version of the node-orm2 adapter and master here ...

**Comment by davewasmer** [comment]
Just curious - why are you passing `--watch` into `denali server`?

**Comment by acorncom** [comment]
Because at the time I didn't realize it was a default for the CLI command ;-)
