### ISSUE TITLE
`denali routes` errors, cannot find app/application

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#155]
```
$ denali routes
Build successful
Error loading your application - expected /app/application.js to exist
Error instantiating application:
Error: Invalid application export
    at /Users/iradchenko/sandbox/denali/dist/lib/cli/lib/project.js:2837:17
    at tryCatch (/Users/iradchenko/sandbox/denali/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/Users/iradchenko/sandbox/denali/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/Users/iradchenko/sandbox/denali/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/Users/iradchenko/sandbox/denali/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

The path points to `dist/app/application` and the file is there transformed. Maybe it's looking for it in denali's dist folder?

**Comment by knownasilya** [comment]
Will try to test this today against master.

**Comment by knownasilya** [comment]
Still an issue.
