### ISSUE TITLE
Add-on issue post broccoli changes

### ISSUE THREAD

**Issue by acorncom** [denali-js/denali#157]
Not sure what to chalk this up to.  But if I've applied https://github.com/denali-js/denali/pull/156 I see the issues below.  The issues in #156 cropped up in changes related to #123 so that's the first place I'll look for this.  But if you guys have any ideas, I'm interested ;-) /cc @davewasmer @knownasilya 

```
machine:~/Sites/open-source/ember-learn/ember-help-wanted-backend (getting-webhook-receiving *)$ denali server

~/Sites/open-source/ember-learn/ember-help-wanted-backend/app/app/actions/webhook/issues.js

Build successful

~/Sites/open-source/denali-js/denali-node-orm2/node_modules/orm/lib/ORM.js:172
				return this.emit("error", new ORMError("Connection lost - driver does not support reconnection", 'CONNECTION_LOST'));
                              ^
[ORMError CONNECTION_LOST: Connection lost - driver does not support reconnection]
    at ORM.<anonymous> (~/Sites/open-source/denali-js/denali-node-orm2/node_modules/orm/lib/ORM.js:172:31)
    at emitOne (events.js:96:13)
    at Database.emit (events.js:188:7)
```

**Comment by acorncom** [comment]
Turns out this was a mixture of my defining a sqlite DB path using a relative path and the updates to the broccoli build system.  Closing this as it's not Denali's issue
