### ISSUE TITLE
Look into bugs with new server smoke tests

### ISSUE THREAD

**Issue by acorncom** [denali-js/denali#173]
Seems related to https://github.com/denali-js/denali/commit/ad7d25ac613a96ebc33a207205a623806386e8db I'm seeing broken tests hitting on my end.

```
  1) server command "before all" hook:
     Error: ENOENT: no such file or directory, symlink '/<path>/open-source/denali-js/denali' -> '<path>/open-source/denali-js/denali/dist/test/fixtures/cli/basic-app/node_modules/denali'
      at Error (native)
      at Object.fs.symlinkSync (fs.js:1054:18)
      at Context.<anonymous> (test/acceptance/cli/server-test.js:23:18)

  2) server command "after all" hook:
     Error: ENOENT: no such file or directory, unlink '/<path>/open-source/denali-js/denali/dist/test/fixtures/cli/basic-app/node_modules/denali'
      at Error (native)
      at Object.fs.unlinkSync (fs.js:1089:18)
      at Context.<anonymous> (test/acceptance/cli/server-test.js:27:18)
```

**Comment by knownasilya** [comment]
I also ran into this #97 after I did the rebase. You should check against #172

**Comment by davewasmer** [comment]
Should be fixed now - and snazzier!
