### ISSUE TITLE
Starting app w/ addon fails on first denali code

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#180]
```
denali server

{ ruleId: 'no-debugger',
  severity: 2,
  message: 'Unexpected \'debugger\' statement.',
  line: 9,
  column: 5,
  nodeType: 'DebuggerStatement',
  source: '    debugger;' }
{ ruleId: 'no-console',
  severity: 2,
  message: 'Unexpected console statement.',
  line: 10,
  column: 5,
  nodeType: 'MemberExpression',
  source: '    console.log(mailer);',
  endLine: 10,
  endColumn: 16 }
Build successful
[2016-10-22T21:11:21.473Z] ERROR - Error loading an addon from /Users/iradchenko/battleground/blah/dist/node_modules/denali-mailer:
[2016-10-22T21:11:21.474Z] ERROR - SyntaxError: Unexpected token import
/Users/iradchenko/sandbox/denali/lib/index.js:28
import 'babel-polyfill';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/iradchenko/battleground/blah/dist/node_modules/denali-mailer/app/addon.js:17:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
Server crashed. waiting for changes to restart ...
```

**Comment by knownasilya** [comment]
It's referencing the non-build version of denali, even though the dist folder has a built one that is transpiled. Maybe I missed a change in the app or addon somewhere..

**Comment by davewasmer** [comment]
I think this is a manifestation of the fact that `discoverAddons()` doesn't currently recurse through the entire addon dependency graph (it only finds top level addons). I think what you are seeing here is the result of (I'm assuming) trying to run `denali server` in an app with a symlinked addon?

If so, what's happening is that the `denali server` command attempts to build your app and it's addons, but only the top level dependencies (i.e. the ones actually listed in your app's package.json, rather than addons of addons). So the mailer addon get's compiled, but the mailer addon declares denali as a dependency itself. And because it's symlinked, when mailer says `require('denali')`, node's module resolution will find mailer's own nested copy of denali, not your consuming app's copy. And since addons aren't built recursively right now (that's the bug), it's finding the unbuilt version of denali nested inside your symlinked addon.

I'll try to get a fix out for the lack of recursion asap

**Comment by davewasmer** [comment]
This should be fixed, but feel free to re-open if it regresses
