### ISSUE TITLE
Can't deploy to now

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#219]
Getting the following error:

```
> make: Entering directory '/home/nowuser/src/node_modules/dc1ba8196115775facd8a7e77d3b9c0387eea5f3/build'
>   SOLINK_MODULE(target) Release/obj.target/.node
>   COPY Release/.node
> gyp info ok 
> make: Leaving directory '/home/nowuser/src/node_modules/dc1ba8196115775facd8a7e77d3b9c0387eea5f3/build'
> node-pre-gyp info ok 
> ▲ npm start
> /home/nowuser/src/node_modules/789f7fed9947f89f736f9264682e0485f3fe27d9/commands/index.js:1
> (function (exports, require, module, __filename, __dirname) { import fs from 'fs';
>                                                               ^^^^^^
> SyntaxError: Unexpected token import
>     at Object.exports.runInThisContext (vm.js:76:16)
>     at Module._compile (module.js:542:28)
>     at Module._extensions..js (module.js:579:10)
>     at Object.require.extensions.(anonymous function) [as .js] (/home/nowuser/src/node_modules/4e8f317e34f8060828b08c5ae281ad1a2a1b7544/lib/node.js:152:7)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/nowuser/src/node_modules/789f7fed9947f89f736f9264682e0485f3fe27d9/bin/denali:44:5)
> Error Error: Command denali server ended with code 1
>     at ChildProcess.<anonymous> (/usr/lib/node_modules/@zeit/ace/build/lib/run.js:1:599)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> (node:158) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command denali server ended with code 1
```

**Comment by davewasmer** [comment]
I don't have any experience using now - is it possible to SSH into a running app? Looks like something in the build step is failing, obviously.

What version of denali? 0.0.13? master?

**Comment by knownasilya** [comment]
Master. I don't think you can ssh in. cc @rauchg

**Comment by davewasmer** [comment]
Looks like some strange stuff is going on with the node_modules dir? Any idea why denali is stored in `node_modules/789f7fed9947f89f736f9264682e0485f3fe27d9`?

**Comment by knownasilya** [comment]
Closed since it's an issue with `now`.
