### ISSUE TITLE
babel-polyfill error

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#221]
```
 ▲ ~/sandbox/community-group-backend denali g mailer invite-organizer                                                           master :: 8h27m :: ⬡

/Users/iradchenko/sandbox/community-group-backend/node_modules/babel-polyfill/lib/index.js:10
  throw new Error("only one instance of babel-polyfill is allowed");
        ^
Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (/Users/iradchenko/sandbox/community-group-backend/node_modules/babel-polyfill/lib/index.js:10:9)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/iradchenko/sandbox/denali/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/iradchenko/sandbox/community-group-backend/node_modules/denali/lib/index.js:29:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/iradchenko/sandbox/denali/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/iradchenko/sandbox/denali/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by davewasmer** [comment]
Blargh - this is annoying. I wish it would just silently fail, or at least give us a flag to allow that.

So right now we have the polyfill in `bin/denali` to ensure that whenever you run a CLI command, the polyfill is present. This is necessary because not all CLI commands end up importing `lib/index.js` (where the other polyfill import lives). And I'd like to keep it that way, since loading `lib/index.js` from the CLI means loading basically the entire framework into memory, which means babel-register transpiling everything, which is a perf hit.

On the other hand, `bin/denali` isn't guaranteed to be invoked every time denali is loaded into the process either (i.e. running `denali serve` actually starts a child process which directly invokes `app/index.js`, so in the actual running server process, `bin/denali` is never loaded).

The only solution I can see here is to wrap the `lib/index.js` import in a try-catch block to swallow that error. Which is ugly, but might be our only option ...

**Comment by davewasmer** [comment]
Hopefully that does the trick - feel free to reopen if not.
