### ISSUE TITLE
File Watcher `beforeRebuild` not a function

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali#223]
Happened when making a change to a file in the app.

```
Uncaught error in Broccoli file watcher:
TypeError: this.beforeRebuild is not a function
    at PausingWatcher.detectChanges (/Users/iradchenko/sandbox/community-group-backend/node_modules/denali/lib/cli/watcher.js:20:32)
    at PausingWatcher.Watcher.check (/Users/iradchenko/sandbox/community-group-backend/node_modules/broccoli/lib/watcher.js:43:28)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
Watcher quitting
```

**Comment by davewasmer** [comment]
* What command were you running?
* What versions (global and local)?

**Comment by knownasilya** [comment]
`denali serve` with all master.
