### ISSUE TITLE
Model throws error when trying to a property to a falsey value

### ISSUE THREAD

**Issue by acburdine** [denali-js/denali#299]
Noticed this a couple of times. Basically if you try to set the value of a model property (in the example below, 'permissions') to null or something falsey, Denali returns this error:

```
TypeError: 'set' on proxy: trap returned falsish for property 'permissions'
    at UpdateMember._callee$ (/Users/acburdine/Sites/tourdefours/api/app/actions/members/update.js:33:13)
    at tryCatch (/Users/acburdine/Sites/tourdefours/api/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/acburdine/Sites/tourdefours/api/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/acburdine/Sites/tourdefours/api/node_modules/regenerator-runtime/runtime.js:116:21)
    at tryCatch (/Users/acburdine/Sites/tourdefours/api/node_modules/regenerator-runtime/runtime.js:64:40)
    at invoke (/Users/acburdine/Sites/tourdefours/api/node_modules/regenerator-runtime/runtime.js:154:20)
    at /Users/acburdine/Sites/tourdefours/api/node_modules/regenerator-runtime/runtime.js:164:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Because it's throwing from the proxy, I'm _pretty_ sure the error is with Denali's model proxy. I'm gonna do some more investigation - if it's actually with the ORM (`denali-node-orm2`), then I'll close this.

**Comment by acburdine** [comment]
Turns out this is a bug in `denali-node-orm2`, closing this 😄
