### ISSUE TITLE
`denali destroy resource <name>` fails spectacularly

### ISSUE THREAD

**Issue by acburdine** [denali-js/denali#305]
After running `denali generate resource <name>` (testing #303), I decided to try the `destroy` command to see what would happen.

This was the output:
```sh
acburdine@acburdine-mbp ~/Sites/tourdefours/api  (master *) $ denali destroy resource client
denali-cli v0.0.11 [local]
denali v0.0.26 [local]

destroy app/actions/clients/create.js
destroy app/actions/clients/destroy.js
destroy app/actions/clients/list.js
destroy app/actions/clients/show.js
destroy app/actions/clients/update.js
skipped app/models/client.js
skipped app/serializers/client.js
Error encountered when running "undefined" command
ReferenceError: id is not defined
    at eval (lodash.templateSources[27]:33:11)
    at filesToDelete.map.filter.filter (/Users/acburdine/Projects/denali/denali/node_modules/denali-cli/src/blueprint.ts:263:79)
    at Array.filter (native)
    at ResourceBlueprint.<anonymous> (/Users/acburdine/Projects/denali/denali/node_modules/denali-cli/src/blueprint.ts:260:8)
    at next (native)
    at /Users/acburdine/Projects/denali/denali/node_modules/tslib/tslib.js:95:75
    at Object.__awaiter (/Users/acburdine/Projects/denali/denali/node_modules/tslib/tslib.js:91:16)
    at ResourceBlueprint.destroy (/Users/acburdine/Projects/denali/denali/node_modules/denali-cli/dist/blueprint.js:187:24)
    at ResourceBlueprint.<anonymous> (/Users/acburdine/Projects/denali/denali/node_modules/denali-cli/src/blueprint.ts:169:18)
    at next (native)
    at /Users/acburdine/Projects/denali/denali/node_modules/tslib/tslib.js:95:75
    at Object.__awaiter (/Users/acburdine/Projects/denali/denali/node_modules/tslib/tslib.js:91:16)
    at ResourceBlueprint.run (/Users/acburdine/Projects/denali/denali/node_modules/denali-cli/dist/blueprint.js:125:24)
    at Function.<anonymous> (/Users/acburdine/Projects/denali/denali/node_modules/denali-cli/src/command.ts:132:21)
    at next (native)
    at /Users/acburdine/Projects/denali/denali/node_modules/tslib/tslib.js:95:75
    at Object.__awaiter (/Users/acburdine/Projects/denali/denali/node_modules/tslib/tslib.js:91:16)
    at Function._run (/Users/acburdine/Projects/denali/denali/node_modules/denali-cli/dist/command.js:58:24)
    at Object.handler (/Users/acburdine/Projects/denali/denali/node_modules/denali-cli/src/command.ts:48:14)
    at Object.self.runCommand (/Users/acburdine/Sites/tourdefours/api/node_modules/yargs/lib/command.js:170:22)
    at parseArgs (/Users/acburdine/Sites/tourdefours/api/node_modules/yargs/yargs.js:920:28)
    at Object.get [as argv] (/Users/acburdine/Sites/tourdefours/api/node_modules/yargs/yargs.js:860:16)
```

None of the files were actually deleted though. I'll do some more checking to see if this occurs in any of the other blueprints.

**Comment by davewasmer** [comment]
Anyone who wants to help on this one, what would be super awesome: a failing test to reproduce this. Should help fixing the bug, and keeping it fixed.

Ideally, the test should cover:

1. `destroy` actually removes blueprint generated files, as well as backs out codemod changes (i.e. an added route to the routes file is removed)
2. If any of the generated files or the codemod changes have been altered from their vanilla blueprint generated state, they are kept.
