### ISSUE TITLE
yarn-related error when spinning up new denali app

### ISSUE THREAD

**Issue by jamesdixon** [denali-js/denali#310]
Spun up a new Denali app (CLI 0.0.11 and Denali 0.0.26) and received the following error:

```
⠏ Installing dependencies with yarnDenali encountered a problem while trying to install the dependencies for your new app:
Error: Command failed: yarn install --mutex network
warning denali-cli > yarn@0.19.1: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
warning ava > babel-preset-es2015-node4@2.1.1: Use npmjs.org/babel-preset-env instead, see https://github.com/babel/babel-preset-env
warning denali-cli > broccoli > findup-sync > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning denali-cli > jscodeshift > babel-core > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
error An unexpected error occurred: "https://registry.yarnpkg.com/babel-plugin-transform-export-extensions/-/babel-plugin-transform-export-extensions-6.22.0.tgz: Request failed \"502 Bad Gateway\"".

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:509:12)
```

After manually running `yarn install`, I was able to start the server.

**Comment by jamesdixon** [comment]
Just an FYI that I deleted the app and tried again -- no errors this time around.
