### ISSUE TITLE
--print-slow-trees not working

### ISSUE THREAD

**Issue by seawatts** [denali-js/denali#374]
```bash
denali build --print-slow-trees=true
cli v0.0.12 [local] | denali v0.0.29 [local]

✖ Build failed
TypeError: broccoli_slow_trees_1.default is not a function
    at Project.finishBuild (/Users/daw/projects/oss/denali/denali-cli/lib/project.ts:320:21)
    at Project.<anonymous> (/Users/daw/projects/oss/denali/denali-cli/lib/project.ts:193:12)
    at Generator.next (<anonymous>)
    at fulfilled (./node_modules/tslib/tslib.js:93:62)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by davewasmer** [comment]
This actually belongs on denali-cli, that's where the relevant code is. Closing in favor of denali-js/denali-cli#33
