### ISSUE TITLE
Issue with denali generate service

### ISSUE THREAD

**Issue by seawatts** [denali-js/denali#380]
```bash
$ denali generate service mixpanel
cli v0.0.12 [local] | denali v0.0.29 [local]

create app/services/mixpanel.js
Error encountered when running "undefined" command
ReferenceError: className is not defined
    at eval (test/unit/services/__name__-test.js:9:11)
    at walk.forEach (/Users/daw/projects/oss/denali/denali-cli/lib/blueprint.ts:211:42)
    at Array.forEach (native)
    at ServiceBlueprint.<anonymous> (/Users/daw/projects/oss/denali/denali-cli/lib/blueprint.ts:181:30)
```

**Comment by davewasmer** [comment]
Sounds like the service blueprint is expecting `className` to be defined by the blueprint `locals()` method, but it isn't?
