### ISSUE TITLE
new denali app does not work

### ISSUE THREAD

**Issue by luxferresum** [denali-js/denali#425]
this can be reproduced with `yarn global add denali denali-cli && denali new blog && cd blog && denali server`. I've also used docker for reproduction.

The following command will produced the following log

> docker run -ti --rm node:7 /bin/bash -c "yarn global add denali denali-cli && denali new blog && cd blog && denali server" 

```
yarn global v0.24.4
[1/4] Resolving packages...
warning denali-cli > yarn@0.27.5: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
warning denali-cli > broccoli > findup-sync > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning denali-cli > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning denali-cli > jscodeshift > babel-core > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[2/4] Fetching packages...
warning fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.3.2" while you're on "0.24.4".
warning "denali@0.0.40" has no binaries
success Installed "denali-cli@0.0.19" with binaries:
      - denali
Done in 59.85s.
cli v0.0.19 [global] | denali v0.0.40 [global]



create blog/.babelrc
create blog/.editorconfig
create blog/.env
create blog/.eslintignore
create blog/.eslintrc
create blog/.gitattributes
create blog/.nvmrc
create blog/.travis.yml
create blog/CHANGELOG.md
create blog/README.md
create blog/app/actions/application.js
create blog/app/actions/index.js
create blog/app/application.js
create blog/app/models/application.js
create blog/app/orm-adapters/application.js
create blog/app/parsers/application.js
create blog/app/serializers/application.js
create blog/app/services/.gitkeep
create blog/config/environment.js
create blog/config/initializers/.gitkeep
create blog/config/middleware.js
create blog/config/routes.js
create blog/denali-build.js
create blog/.gitignore
create blog/index.js
create blog/package.json
create blog/test/.eslintrc
create blog/test/acceptance/index-test.js
create blog/test/helpers/.gitkeep
create blog/test/unit/.gitkeep
✔ Dependencies installed
✖ Unable to initialize git repo:
Error: Command failed: git commit -am "Initial denali project scaffold"

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@1d364a21ba0d.(none)')

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)
📦  blog created!

To launch your application, just run:

  $ cd blog && denali server

cli v0.0.19 [global] | denali v0.0.40 [local]

NestedError: "server" command failed
    at Function.<anonymous> (/blog/node_modules/denali/node_modules/denali-cli/dist/lib/command.js:38:23)
    at Generator.throw (<anonymous>)
    at rejected (/blog/node_modules/tslib/tslib.js:105:69)
    at runMicrotasksCallback (internal/process/next_tick.js:64:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
Caused By: TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/blog/node_modules/denali/denali-build.js:6:46)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Function.createFor (/blog/node_modules/denali-cli/dist/lib/builders/base.js:41:38)
    at find_plugins_1.default.map (/blog/node_modules/denali-cli/dist/lib/builders/base.js:87:32)
    at Array.map (native)
    at BlogBuilder.discoverAddons (/blog/node_modules/denali-cli/dist/lib/builders/base.js:85:12)
    at BlogBuilder.BaseBuilder (/blog/node_modules/denali-cli/dist/lib/builders/base.js:26:28)
    at AppBuilder (/blog/node_modules/denali-cli/dist/lib/builders/app.js:12:1)
    at BlogBuilder (/blog/denali-build.js:3:18)
    at Function.createFor (/blog/node_modules/denali/node_modules/denali-cli/dist/lib/builder.js:96:43)
    at Project.createRootBuilderAndTree (/blog/node_modules/denali/node_modules/denali-cli/dist/lib/project.js:85:50)
    at new Project (/blog/node_modules/denali/node_modules/denali-cli/dist/lib/project.js:54:14)
    at ServerCommand.run (/blog/node_modules/denali/dist/commands/server.js:26:23)
    at Function.<anonymous> (/blog/node_modules/denali/node_modules/denali-cli/dist/lib/command.js:35:31)
    at Generator.next (<anonymous>)
    at /blog/node_modules/tslib/tslib.js:107:75

```

**Comment by knownasilya** [comment]
I think @davewasmer is in the process of finishing up some changes, and some have been published but not all. I think he had a goal of Feb 15th to have something closer to a beta.

**Comment by luxferresum** [comment]
That would be awesome. I'm currently experimenting with nest, but really would love something more ember-ish.

**Comment by davewasmer** [comment]
@luxferresum yep, what @knownasilya mentioned. There were some big changes that needed to happen under the hood, which took a while, so I unfortunately let the published versions languish a bit. But hoping to get new versions and docs out in the next few days. Keep your eye out for 'em!

**Comment by luxferresum** [comment]
seems working now so I close this
